name: Auto Merge

on:
  push:
    branches:
      - 'feature/**'
      - 'bugfix/**'

jobs:
  buildJob:
    runs-on: ubuntu-latest
    steps:
      ##################
      # pre jobs START #
      ##################
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15
      - uses: actions/cache@v2
        id: lerna-cache
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/yarn.lock') }}
      - run: npm run _:package:bootstrap
        if: steps.lerna-cache.outputs.cache-hit != 'true'
      ################
      # pre jobs END #
      ################
      - run: npm run test

  mergeJob:
    runs-on: ubuntu-latest
    needs:
      - buildJob
    steps:
      - uses: actions/checkout@v2
      - uses: everlytic/branch-merge@1.1.0
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: 'master'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
      # todo 실패시 슬랙 노티

#  delete-branch:
#    runs-on: ubuntu-latest
#    needs:
#      - test-job
#      - merge-branch
#    steps:
#      - name: Delete branch in specific repository with a specific owner
#        uses: dawidd6/action-delete-branch@v3
#        with:
#          github_token: ${{ github.token }}
#          branches: true
